zuul:
  routes:
       comment:
           path: /book/**
           service-id: book  
server:
  port: 8080
  
  
spring:
  application:
    name: Zuul 
eureka:         
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
 